export const SET_VISITOR_STATE = 'SET_VISITOR_STATE';

export const CONNECTION_CHANGE_START = 'CONNECTION_CHANGE_START';
export const CONNECTION_CHANGE_SUCCESS = 'CONNECTION_CHANGE_SUCCESS';
export const CONNECTION_CHANGE_FAILURE = 'CONNECTION_CHANGE_FAILURE';

export const VALIDATE_PLATFORM = 'VALIDATE_PLATFORM';
export const VALIDATE_CARRIER = 'VALIDATE_CARRIER';

export const RECIEVED_CARRIER_LIST_START = 'RECIEVED_CARRIER_LIST_START';
export const RECEIVED_CARRIER_LIST_SUCCESS = 'RECEIVED_CARRIER_LIST_SUCCESS';
export const RECEIVED_CARRIER_LIST_FAIL = 'RECEIVED_CARRIER_LIST_FAIL';

export const UPDATE_VISITOR_CARRIER_START = 'UPDATE_VISITOR_CARRIER_START';
export const UPDATE_VISITOR_CARRIER_SUCCESS = 'UPDATE_VISITOR_CARRIER_SUCCESS';
export const UPDATE_VISITOR_CARRIER_FAIL = 'UPDATE_VISITOR_CARRIER_FAIL';