export const SET_VISITOR_STATE = 'SET_VISITOR_STATE';

export const CONNECTION_CHANGE_START = 'CONNECTION_CHANGE_START';
export const CONNECTION_CHANGE_SUCCESS = 'CONNECTION_CHANGE_SUCCESS';
export const CONNECTION_CHANGE_FAILURE = 'CONNECTION_CHANGE_FAILURE';

export const VALIDATE_PLATFORM = 'VALIDATE_PLATFORM';
export const VALIDATE_CARRIER = 'VALIDATE_CARRIER';
export const VALIDATE_SEARCH = 'VALIDATE_SEARCH';